### PR TITLE
0.1.0 version

### PR DESCRIPTION
**Pull request by slazicoicr**
Before replacing bamQC with smallBamQc in emSeqQc, I want to run smallBamQc against lots of libraries and compare it to bamQC output. Once that looks good, I'll do a 1.0.0 release.

### CODE REVIEW

**Comment by bibilujan** [comment]
Looks good. 
What is the use case for the "reads to use" for the different tasks? Would this be used if you only want to QC a set number of reads? it looks like it would grab the first n reads, not randomized. Is that correct?

**Comment by slazicoicr** [comment]
The "reads to use" is for down sampling. For example, we don't need all reads to calculate mean insert size, coverage, or duplication rate. Each task can have different down sampling, as each task has different sensitivity to down sampling. Downsampling is optional and is off by default. You are correct that you get the first N number of reads. See [design](https://github.com/oicr-gsi/smallBamQc/blob/dev/DESIGN.md) docs for full details. In short, the design was to be as fast as possible. Random exact sampling is very slow. It has to go through the whole BAM file (very slow IO operation) and do some extra complexity and loss of efficiency to get exact downsampling (https://github.com/oicr-gsi/bamQC/blob/master/bamQC.wdl#L454). I tested first N downsampling against random downsampling for Picard MarkDuplicates, where bamQc randomly downsamples to 1 million reads. I did not see any difference. I will repeat this test with this version of smallBamQc across 100s of BAM files with bamQC output to get a more definitive answer.

**Comment by bibilujan** [comment]
Very interested to follow your comparison work, to see how the data and performance compares to bamQc

**Review by bibilujan — APPROVED** [review]

**Comment by gavin-peng** [comment]
bamQC now is aiming at handling multile bams input: https://jira.oicr.on.ca/browse/GRD-658. Does smallBamQC has similar consideration?
crosscheckFingerprintsCollector used to bottleneck at markDuplicates task when got big bam inputs, and very memory demanding. Now it's scatter over chromosomes:
 https://github.com/oicr-gsi/crosscheckFingerprintsCollector/blob/main/crosscheckFingerprintsCollector.wdl#L150
 then it's much more reliable and faster. Consider doing this in smallBamQc task?

**Comment by slazicoicr** [comment]
Multiple bams: No multiple BAM files for this version, as emSeqQc doesn't need this feature. Once this workflow is shown to work and scope increases, merging can be considered.

scatter markDuplicates: our current bamQC takes 1 million reads to calculate duplication rate, which is accurate. `scatter` would greatly increase the footprint of this workflow (16GB per instance * 23 chromosomes vs just 16GB), without providing any benefit.

**Review by gavin-peng — APPROVED** [review]

**Pull request merged**
